apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
  - name: api-container
    image: moumani/api-image:latest
    ports:
    - containerPort: 3000
    
    ---
    
    
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
spec:
  containers:
  - name: frontend-container
    image: moumani/frontend-image:latest
    ports:
    - containerPort: 80
    
    ---
    
apiVersion: v1
kind: Pod
metadata:
  name: quote-pod
spec:
  containers:
  - name: quote-container
    image: moumani/quote-image:latest
    ports:
    - containerPort: 5000
